# Generated by Django 4.1.5 on 2023-01-16 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statusdriver',
            name='point',
        ),
        migrations.AddField(
            model_name='statusdriver',
            name='raiting',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
